[package]
name = "rsnano_nullable_tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
rsnano_output_tracker = { path = "../output_tracker" }
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "macros",
    "sync",
	"io-util"
] }

[target.'cfg(windows)'.dependencies]
socket2 = "0.5"
